name: install_pytorch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    # paths:
    # - 'buster_build/Dockerfile'
    # - '.github/workflows/build_buster_build.yml' # Trigger also on update of the workflow

jobs:

  build_1:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install QEMU
      run: sudo apt-get update && sudo apt-get install qemu-user-static qemu binfmt-support
    - name: Create docker container
      run: docker create --name build choonkiatlee/raspbian:build qemu-arm-static /bin/bash /install_pytorch.sh
    - name: Copy Script
      run: docker cp install_pytorch.sh build:/install_pytorch.sh
    - name: Build and commit
      run: |
        docker start build
        docker attach build
        docker commit build build-intermediate
        docker tag build-intermediate choonkiatlee/pi-torch:build-intermediate
    - name: compile and push
      run: |
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        docker push choonkiatlee/pi-torch:build-intermediate

  build_2:

    runs-on: ubuntu-latest

    steps:

    - name: Install QEMU
      run: sudo apt-get update && sudo apt-get install qemu-user-static qemu binfmt-support
    - name: Pull Docker container
      run: |
        docker run --name build choonkiatlee/pi-torch:build-intermediate qemu-arm-static /bin/bash cd pytorch; timeout -s SIGINT 18000 python3 setup.py bdist_wheel
        docker attach build
    - name: Pull image
      run: mkdir output; docker cp build:/pytorch/dist/. output/.
    - name: Upload pytorch artifact
      uses: actions/upload-artifact@v1
      with:
        name: compiled_output
        path: output